### ISSUE TITLE
Melpa Stable at 0.12.108 but no pre-compiled grammar binaries available

### ISSUE THREAD

**Issue by nga888** [emacs-tree-sitter/tree-sitter-langs#383] opened 2024-02-13 17:44 UTC
I just did a package update in Windows Emacs 29.2 and the update to 0.12.108 has failed because `tree-sitter-grammars.x86_64-pc-windows-msvc.v0.12.108.tar.gz` is "Not Found". Looking here on GitHub, it looks like the latest release should be 0.12.96 and not 0.12.108.

Thanks.

**Comment by jcs090218** [comment] 2024-02-13 18:07
Version `0.12.96` is correct. Not sure why Melpa Stabel has `0.12.108` since the version hasn't been tagged. 🤔

**Comment by nga888** [comment] 2024-02-13 18:59
I saw this on Melpa: https://github.com/melpa/melpa/commit/f07a741d1a14f99a634041cc9b4c200e75461ae5. Could this be related? Although this was done a few years ago.

**Comment by timcharper** [comment] 2024-02-15 10:14
Still an issue; now it's at 0.12.112

Totally broke my emacs and not sure how to downgrade on melpa.

To workaround, I ran this:

```
cd ~/emacs.d/elpa/tree-sitter-langs-0.12.112/bin
curl -LO https://github.com/emacs-tree-sitter/tree-sitter-langs/releases/download/0.12.96/tree-sitter-grammars.x86_64-unknown-linux-gnu.v0.12.96.tar.gz
tar -xvzf tree-sitter-grammars.x86_64-unknown-linux-gnu.v0.12.96.tar.gz
echo "0.12.112" > BUNDLE-VERSION
```

**Comment by jcs090218** [comment] 2024-02-15 10:20
I've fixed the release pipeline so this issue should be resolved as soon as the `0.12.113` bundled is built. 

Still don't know why Melpa Stable is building it. 🤔

**Comment by jcs090218** [comment] 2024-02-16 02:53
It should be fixed by now.

**Closed by jcs090218** 2024-02-16 02:53 UTC

**Comment by timcharper** [comment] 2024-02-16 07:16
Confirmed fixed! Thank you, @jcs090218
