### ISSUE TITLE
Tree-sitter doesnt work for swift

### ISSUE THREAD

**Issue by konrad1977** [emacs-tree-sitter/tree-sitter-langs#71] opened 2022-01-29 08:49 UTC
I cannot get tree-sitter to work with Swift.

I am new to emacs. So it would be understandable that Its my configs fault instead of this package.

My config:

```
(use-package tree-sitter
  :init
  (global-tree-sitter-mode))

(add-hook 'tree-sitter-after-on-hook #'tree-sitter-hl-mode)

(use-package tree-sitter-langs
  :after (tree-sitter))

```

<img width="1792" alt="Skärmavbild 2022-01-29 kl  09 46 42" src="https://user-images.githubusercontent.com/4384932/151654460-6d1f34a7-814c-411c-a6a2-3307687b905f.png">

**Comment by ubolonton** [comment] 2022-01-29 15:31
This is a duplicate of https://github.com/emacs-tree-sitter/elisp-tree-sitter/discussions/207.

**Closed by ubolonton** 2022-01-29 15:31 UTC

**Comment by konrad1977** [comment] 2022-01-29 15:59
Ah sorry, I thought this was separate projects. Thanks.

**Comment by ubolonton** [comment] 2022-01-29 16:01
No worry. It's indeed a separate project, but doesn't have a discussion area of its own. We use https://github.com/emacs-tree-sitter/elisp-tree-sitter/discussions for that.
